### ISSUE TITLE
Admin app seems to very CPU intensive with nothing even happening

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/sitefinity-admin-app-extensions#118]
Video: https://www.screencast.com/t/3bo6muzHL7ar

There's only 1 content item on the page and nothing happening that I can see.  It only spikes IN the adminapp, not on dash or old UI.

**Comment by sitefinitysteve** [comment]
Closing, tracked it down to the MetaMask chrome extension... the tab still uses a ton of memory, but I suppose that can't be helped

So, I noticed TWITTER is being loaded into an iframe as well, what on EARTH is that about and why is it needed?



<script type="text/javascript" charset="utf-8" async="" src="https://platform.twitter.com/widgets.js"></script>

**Comment by Novkirishki** [comment]
Hi,

Twitter scripts are used in order to embed tweets inside the Rich text editor.

Regards,
Niki
