### ISSUE TITLE
Custom page field

### ISSUE THREAD

**Issue by dondracek** [Sitefinity/sitefinity-admin-app-extensions#125]
As a developer, I would like to add be able to define fields to fetch from the sitefinity backend to display in the grid. For example: a page might be related to specific brands, so there's a custom flat-taxonomy-based field "brands" on page level.
The field appears in the metadata, but it's not fetched when the list of pages is displayed. How can I achieve this?

**Comment by Novkirishki** [comment]
Hi, 

You will have to make an additional call to the web services and specify the Related data/Taxonomy property in an expand clause in order to get the pages (or a specific page) populated with it.

Regards
