### ISSUE TITLE
Getting 404 Error

### ISSUE THREAD

**Issue by salampv** [Sitefinity/sitefinity-admin-app-extensions#133]
Hi, I am getting 404 error in console while saving config.

GET http://localhost:60880/sf/system//Default.AuthSettings(clientId='sitefinity') 404 (Not Found)
Http failure response for http://localhost:60880/sf/system//Default.AuthSettings(clientId='sitefinity'): 404 Not Found
undefined

I already configured web service and STS as mentioned [here](https://github.com/Sitefinity/sitefinity-admin-app-extensions#configure-sitefinity-cms-for-development-of-custom-extensions) and restarted multiple times.
Anyone faced this issue and what is the solution for this?

Thanks and Regards
Muhammed Abdussalam

**Comment by Novkirishki** [comment]
Hi, 

What version of Sitefinity are you using? What version of the extension are you using (latest master or a tagged version)?

It seems to me there is a mismatch between these two. Have you checked the [quick start](https://github.com/Sitefinity/sitefinity-admin-app-extensions#quick-start). There is an explanation how to get the right extensions tag for a specific Sitefinity version.

Regards,
Niki
