### ISSUE TITLE
When clicking on a page to edit during development takes you to host server

### ISSUE THREAD

**Issue by johnlister** [Sitefinity/sitefinity-admin-app-extensions#167]
When running the admin app in development mode locally, if I navigate to the pages view and click on a page to edit in order to test content editor extensions, I'm taken to the edit page on the host Sitefinity site and not within the local environment. Modifying the edit page url to change the host/port to match the local development environment results in a page not found error.

I've followed the instructions and configured Sitefinity as described and all other functionality works. 

This result in being unable to easily test content editor extensions

**Comment by Novkirishki** [comment]
Hi John,

This is the current behavior - pages are edited in the context of the Sitefinity site. 

You can test your content editor extension in any content type that has a long text field (for example NewsItems -> Content).

Regards,
Niki

**Comment by johnlister** [comment]
Many thanks for quick response
