### ISSUE TITLE
Translation actions in Edit view remain visible even when all content type fields are not localizable

### ISSUE THREAD

**Issue by relizondobarrios** [Sitefinity/sitefinity-admin-app-extensions#218]
When you create a content type with all fields as "No Localizable" the translation conlumn in the List view does not displayed (is is perfect and as expected) 
![image](https://user-images.githubusercontent.com/5805778/91493316-5cdc1900-e874-11ea-84d4-24f1bec5409c.png)

But the translation action remains visible.
![image](https://user-images.githubusercontent.com/5805778/91493449-8f861180-e874-11ea-884f-b62698d03f6a.png)

Also, we tried to remove the "Translations" column with getColumnsToRemove() and we experienced the same situation: in List or Grid view, the column is removed but in edit view the translation actions remain visible.

**Comment by Novkirishki** [comment]
Fixed in [13.1.7425.0](https://github.com/Sitefinity/sitefinity-admin-app-extensions/releases/tag/13.1.7425.0)
