### ISSUE TITLE
NOTIFICATION_SERVICE triggers an error in Sitefinity Backend

### ISSUE THREAD

**Issue by relizondobarrios** [Sitefinity/sitefinity-admin-app-extensions#234]
When you inject NOTIFICATION_SERVICE inside a component, the notification component works as expected in **AdminApp** (running 'npm start' command) 

![image](https://user-images.githubusercontent.com/5805778/98016027-16022680-1dc3-11eb-93d9-2104cbe49cbf.png)

But when you run 'npm run build' and put the sample.extensions.bundle.js and sample.extensions.bundle.js.map files in the Sitefinity AdminApp folder, you get a console error and the component is not rendered. 

This is the console error
![image](https://user-images.githubusercontent.com/5805778/98015906-ef43f000-1dc2-11eb-9072-0d1239a27d9b.png)

**Comment by Novkirishki** [comment]
Hi @relizondobarrios ,

I tried to reproduce the issue, but was unable to do so. Can you please give us more details about the reproduction scenario or provide us with a sample that demonstrates it.

Regards

**Comment by relizondobarrios** [comment]
Hello @Novkirishki,

I checked my implementation again using the "progress-sitefinity-adminapp-sdk": "13.1.7424"; and now there is no error. 

Thanks a lot
