### ISSUE TITLE
Allow us to edit the ordinal for custom grid columns

### ISSUE THREAD

**Issue by dehivis24** [Sitefinity/sitefinity-admin-app-extensions#239]
Hello,

This is not an issue but more of a feature request. 
In our Sitefinity project we have several custom grid columns in our content types maintenances and we noticed that all of those columns are located at the end of the grid.
![image](https://user-images.githubusercontent.com/69977848/99409056-90986f00-28b6-11eb-9867-36ca02f0374f.png)

As you can see in the image the Product Description is a custom grid and it is displayed as the last column but it would make more sense if this column was displayed next to the Product Number, so my question is: Is there a way in which we can modify the order of these custom grid columns?

Thanks.

**Comment by Novkirishki** [comment]
Hi @dehivis24, 

Currently there is no way to modify the order of the custom columns. I am going to mark this as a feature request. 

Regards

**Comment by IrenaPankova** [comment]
Fix is provided in Sitefinity CMS 13.2.7525 (Patch)
