### ISSUE TITLE
Issue in Content Types that have children content types regarding columns: Author, Last Modified & Created on

### ISSUE THREAD

**Issue by dehivis24** [Sitefinity/sitefinity-admin-app-extensions#264]
Hello,
We found an issue in Content Types that have children content types. 
The issue is that columns “Author”, “Last Modified” and “Created on” columns are not displayed even if they are selected in the Backend screens tweaks.

![image](https://user-images.githubusercontent.com/69977848/104627752-0b82c980-565d-11eb-8cad-fc9310edf533.png)

Content types that do not have children content types show those columns so we were wondering if they could be displayed for the parent ones as well.

Thanks.

**Comment by belchevgb** [comment]
Hi @dehivis24, currently this is by design, but we can introduce a way to configure if this columns should be visible. Thanks for the report.

**Comment by IrenaPankova** [comment]
Fix is provided in Sitefinity CMS 13.2.7525 (Patch)
