### ISSUE TITLE
Actions columns position in Backend screen tweaks does not match its position in the grid view

### ISSUE THREAD

**Issue by dehivis24** [Sitefinity/sitefinity-admin-app-extensions#265]
Hello,
We found an issue regarding the "Actions" columns position in Backend screen tweaks because it does not match its position in the grid view.
Backend screen tweaks:
![image](https://user-images.githubusercontent.com/69977848/104746357-c621d300-5714-11eb-8403-0c8df451cb9d.png)

Grid view:
![image](https://user-images.githubusercontent.com/69977848/104746436-e6519200-5714-11eb-8889-caf616b4c83b.png)

Thanks.

**Comment by belchevgb** [comment]
Hi @dehivis24. This is not a bug. The actions column is statically last by design. This reflects only the new UI.
