### ISSUE TITLE
Single Related Data field in the column grid not displaying value 

### ISSUE THREAD

**Issue by dehivis24** [Sitefinity/sitefinity-admin-app-extensions#358]
Hello,
This issue occurs only when you are working with projects that have been previously upgraded. It works correctly with new Sitefinity projects.
In our case, we have a content type with a related data field with Pages and in the grid we display this field as a column but it doesn't display any of the names of the pages and there are errors in the browser console.

![image](https://user-images.githubusercontent.com/69977848/131908960-24321b47-2a5f-4c46-a61e-f300b816c233.png)

![image](https://user-images.githubusercontent.com/69977848/131909011-32bfe0f1-2def-4b3c-85b7-ee3ab4dd19aa.png)

We tried to reinstall admin app extensions following this Sitefinity post, but it didn't work.
https://knowledgebase.progress.com/articles/Article/AdminApp-How-to-reinstall-the-new-backend-experience

We are currently working with version 13.3.7600.

Any ideas on what could be causing this problem?

Thanks.

**Comment by Novkirishki** [comment]
Hi @dehivis24,

This issues does not seem like it is related to the Admin App extensibility project. 

Can you please [open a ticket](https://www.progress.com/support/sitefinity-log-support-case) for our support team?
