### ISSUE TITLE
Publishing a large number of content items gets stuck

### ISSUE THREAD

**Issue by dehivis24** [Sitefinity/sitefinity-admin-app-extensions#359]
Hello,
In our project, we have a Products module that has a large number of content items (> 137000) and whenever we select all of them to be published, we notice that a lot of requests are executed.

![image](https://user-images.githubusercontent.com/69977848/131932336-c4b7ce27-59ff-4120-8dbb-834ead676bba.png)

The first set of requests that are executed are 'GET' requests which retrieve the Ids of all content items to be published.
The second set of requests are POST and those are the ones that publish the content items one at a time.

The behavior that we are experiencing is that these requests get slower and slower over time. 
After a few thousand requests are executed, we noticed that fewer requests are executed by second. 
We even had a timeout and the publishing process was canceled, we believe that this happened because of the number of requests that were being executed.

We wanted to ask you if there was a better way to publish a large number of content items without having to execute so many requests.

Thanks.

**Comment by Novkirishki** [comment]
Hi @dehivis24,

you can use Sitefinity Native API to achieve the desired behavior. Here is a sample with News:

https://www.progress.com/documentation/sitefinity-cms/for-developers-create-a-news-item-with-the-native-api

You can create a custom operation that will call a custom OData endpoint which will execute the publishing logic. For such a large portion of items I would suggest you to batch them (for example 1000 items per batch) and call SaveChanges() once on every batch.
