### ISSUE TITLE
create a button on the list view backend screen not working

### ISSUE THREAD

**Issue by atrivedi-affirma** [Sitefinity/sitefinity-admin-app-extensions#379]
This is not working in sitefinity version 13.3. Till 12.0, Custom button was working.

**Comment by Novkirishki** [comment]
Hi @atrivedi-affirma ,

In the period between 12.0 and 13.3 we did an angular update that contained a breaking change. Can you try rebuilding your extension after pulling from the branch corresponding to Sitefinity 13.3

**Comment by atrivedi-affirma** [comment]
We already did that but still it is not working. Other changes are reflected for commands in UI. But specifically Custom button 'Export' beside 'new item' not visible on UI on dynamic content type

**Comment by Novkirishki** [comment]
Hi @atrivedi-affirma,

Sorry for the delayed response. In order for the custom button to be visible in the grid view,  the command should have a category named 'Default'. 

In case this does not help, can you send us a code sample (a fork would be perfect) where we can reproduce and investigate the problem.

**Comment by atrivedi-affirma** [comment]
Hi,

Thank you. You are correct and it is working fine now.

**Comment by Novkirishki** [comment]
Thank you for the response.
