### ISSUE TITLE
Filtering on related data [tree node] field

### ISSUE THREAD

**Issue by shreeramghatwai** [Sitefinity/sitefinity-admin-app-extensions#387]
Hi,

there is no provision in related data [tree node] control to filter the component data as per our need, if we try to modify it is not working , do we have any solution or alternative to use a filter on ComponentData of the getComponentData of the TreeNodeComponentProvider in related data.

**Comment by shreeramghatwai** [comment]
Hi,

Can anyone please reply on this raised question?

**Comment by stefankoserkov** [comment]
Hello @shreeramghatwai 

Please excuse us for the delayed response.

Please correct me if I have not understood your question.

The ComponentData object that should be returned by the getComponentData method, is something that the developer declares and returns. If your case is that you would like to use different angular components for the same entity set (i.e. newsitems), that is something that should be handled with templates or other logic in the component that is returned in the ComponentData object that you declare and return.

Best regards, 
Stefan

**Comment by shreeramghatwai** [comment]
Hi @stefankoserkov ,

Thanks for your reply. My main goal is to filter the items in getcomponentData method but i dont see any option available there hene raising this concern that how we can achieve this? If you have done something similar to this please guide.

Ragards,
Shriram

**Comment by stefankoserkov** [comment]
Hello @shreeramghatwai,

The intent of the method `getComponentData()` is to return data that specifies what angular component should be rendered for which feature (currently only related data is supported) and for which entity set. This method does not "know" the particular content items that it will get in advance. The content items are never passed as a collection of any kind, anywhere in this extension. You will only get the content item that is currently being rendered your custom component in the field `@Input() item: DataItem;` and based on data in this item and an [angular component lifecycle hook](https://angular.io/guide/lifecycle-hooks) you can determine what to render in your custom angular component. 

Let's take the example in the [documentation for this extension](https://github.com/Sitefinity/sitefinity-admin-app-extensions/tree/master/src/tree#custom-list-components). The intent of this extension is to render a custom angular component all thought the application where a custom field of type related data for news items has been added. 

Please let me know if you have any further questions.

Best regards,
Stefan

**Comment by shreeramghatwai** [comment]
Hi @stefankoserkov, 

Completely agree with your comment but my query remains same that whether we can filter out the in getComponentData()  method because there are 10k present in newsitems and I want only selected news items i.e. based upon certain condition news items should appear. as you have mentioned here in this "You will only get the content item that is currently being rendered your custom component in the field @Input() item: DataItem; and based on data in this item" I am not able to filter out the data directly or there is no method available to filter out the DataItem. If you could please provide any filter related DataItem example , that will solve my problem.

Thanks & Regards,
Shriram

**Comment by shreeramghatwai** [comment]
Hi @stefankoserkov,

It means there is no filtration available in current context of sitefinity, its a strange that sitefinity also doesn't provide any alternates to achieve this in the backend / admin. it is available in frontend where we need to select related data type as master / detail. 

to answer to your ngOnInit , I am able to modify the look & feel of each Single item  in related data but it works on inside tree component , due to presence of parent css selector it renders like below, the one which binds the data fulfills the ngIf condition but the one which is looking empty is due to parent css selectors. Do you have any info to stop this kind of rendering.

![image](https://user-images.githubusercontent.com/95875758/148094855-166ddfa6-6830-4734-bf45-34abe92ccf9c.png)

**Comment by shreeramghatwai** [comment]
Hi,

Do you have any solution for the above mentioned issue i.e. rendering due to parent css selectors

**Comment by stefankoserkov** [comment]
Hi, 

The intent of this extension is to modify the look of the components rendered in the tree, currently, no filtration is supported, and will probably not be supported since the custom fields hold items that are handpicked from the selectors, and the selectors should show all items available to the current user based on sites/providers/permissions. 

If your request is to apply the custom component for a select few content items of a certain type, this is also not intended and you must handle this logic in your custom implementation. 

You cannot stop the rendering of the parent component that holds your custom component.

If you have any further questions, please submit a [support case](https://www.progress.com/support/sitefinity-log-support-case).

Best regards,
Stefan
