### ISSUE TITLE
TextArea support for Custom Fields Provider

### ISSUE THREAD

**Issue by kevindenham** [Sitefinity/sitefinity-admin-app-extensions#414]
I've attempted to use the custom fields provider sample but applied to a Long Text (non-Html) instead of a Short Text field. 

Below are the modifications I've made to the sample, but the field shows up to content editors as an `<input>` element rather than the expected `<textarea>`.

Change to custom-fields-provider.ts 
`        const customInputKey: FieldData = {
            fieldName: "Summary",
            fieldType: FieldTypes.textArea,
            typeName: "events"
        };`

Change to custom-field-write-component.html:
`<sf-input
    [name]="settings.key"
    [look]="settings.look"
    [type]="textarea"
    [placeholder]="settings.placeholder"
    [recommendedCharacters]="settings.recommendedCharacters"
    #inputField
    ngDefaultControl
    [(ngModel)]="value"
    (onBlur)="onBlur()"
    (onFocus)="onFocus()">
</sf-input>
`

**Comment by stefankoserkov** [comment]
Hi @kevindenham,

Sorry for the delay,

The type attribute needs to be a string, `[type]="'textarea'"` in order for it to have effect.

Best regards,
Stefan
