### ISSUE TITLE
Error when running nom start on master branch

### ISSUE THREAD

**Issue by sethprogress** [Sitefinity/sitefinity-admin-app-extensions#42]
Error when running nom start on master branch

ERROR in [at-loader] ./switch-text-direction/switch-text-direction.provider.ts:2:65
    TS2305: Module '"/Users/sethcleaver/Projects/Sitefinity/sitefinity-admin-app-extensions/node_modules/progress-sitefinity-adminapp-sdk/app/api/v1/index"' has no exported member 'groupToolbarButtons'.

**Comment by Novkirishki** [comment]
The error was due to the fact the extensions were not using the latest version of the _progress-sitefinity-adminapp-sdk_ package. It is fixed now.
