### ISSUE TITLE
Issue with SEO and Open Graph fields (Title and Description)

### ISSUE THREAD

**Issue by dehivis24** [Sitefinity/sitefinity-admin-app-extensions#446]
Hello,
We are having a strange behavior with the SEO and Open Graph fields (Title and Description). 
According to the Sitefinity documentation, these fields are filled out with the content of the first text field after the title field of the content item. 
https://www.progress.com/documentation/sitefinity-cms/configure-meta-title-and-meta-description

This is behaving as the documentation says but when I click on Publish or Save as Draft, the values that were filled out are not saved in the database. It seems that the behavior described in the documentation is visual only, the problem with this is that the user would not be able to know if the value is already saved in the DB or not.

![image](https://user-images.githubusercontent.com/69977848/175431641-c1aad383-4a33-44f8-9cf1-5e6ad4106c74.png)

So we were wondering if you could change this behavior so that those values ​​are stored in the database when the user clicks Publish or Save as Draft; or if those fields have an empty value in the database, the values ​​that are populated are seen as in a placeholder format. For example:

![image](https://user-images.githubusercontent.com/69977848/175432469-6b0a3668-3857-4591-bd34-9144ebb81465.png)

Thanks.

**Comment by Novkirishki** [comment]
Hi, 

The bahavior that you described is by design and will not be changed.

Regards,
Niki
