### ISSUE TITLE
Override a Custom field type Choice is not working after upgrade to Sitefinity version 14.3

### ISSUE THREAD

**Issue by ronnyvasquez-cr** [Sitefinity/sitefinity-admin-app-extensions#483]
After an upgrade of Sitefinity to version 14.3.8022.0 (from 13.3.7600.0), an error shows up in js when overriding a Custom filed - type Choice: settingsCast.updateHasFieldset is not a function.

![Custom filed - type Choice](https://user-images.githubusercontent.com/54782170/207887245-7e176dd8-989b-4080-a19d-76ee862edaea.jpg)

**Comment by Novkirishki** [comment]
Hello @relizondobarrios @ronnyvasquez-cr,

thank you for reporting this behavior to us. Sorry for not responding to the initial issue, we have missed the notificaiton from GitHub. 

I can confim that this is a bug in Sitefinity (not in the Admin App Extensions project). Therefore we will provide a fix in the upcoming Sitefinity patch 14.4.8124, which will be released in 2 to 3 weeks time. 

Best,
Niki
