### ISSUE TITLE
AdminApp: RTL extension not working after upgrade

### ISSUE THREAD

**Issue by phuongtm11** [Sitefinity/sitefinity-admin-app-extensions#540]
Hi, after an upgrade of Sitefinity to version 14.4..., an error shows up related to Rich Text Editor on News content. The format of tool broken and can not click anything
![image](https://github.com/Sitefinity/sitefinity-admin-app-extensions/assets/122333465/f4a86458-fea5-487d-8349-92b06785f42a)

We also noticed that the class of HTML tag is not correct when I compare with clean Sitefinity project
**On my Siteifnity own project**
![image](https://github.com/Sitefinity/sitefinity-admin-app-extensions/assets/122333465/5bc087ae-1cf7-4653-9afa-f1c87afbaa0c)

**On my clean Sitefinity Project**
![image](https://github.com/Sitefinity/sitefinity-admin-app-extensions/assets/122333465/88877dc3-a367-4f2f-ba28-bb730f50a66e)

**Comment by annix8** [comment]
Hi,

Can you, please, provide the message/stack trace of the error?

**Comment by phuongtm11** [comment]
Hi annix8,

It got a error on Console log but this look not related to RTE issue.
![image](https://github.com/Sitefinity/sitefinity-admin-app-extensions/assets/122333465/0309e4e6-6106-4996-91d0-f416ebcc685e)

**Comment by annix8** [comment]
Did you try to rebuild the extensions the way I suggested above?

**Comment by phuongtm11** [comment]
Hi Annix8,

I already fixed this issue by another way and it really work well. I tried to "Restore to default" of Rich Text editor in Setting > Backend Interface. Thank for your help!

**Comment by annix8** [comment]
Hi,

I am glad you resolved the issue!

Regards
