### ISSUE TITLE
Extending Existing Functionality

### ISSUE THREAD

**Issue by vesrah** [Sitefinity/sitefinity-admin-app-extensions#60]
Is the code for existing Iris functionality available so that we can extend existing toolbar components such as Formatting or adding a custom field to the Image/Link embed, if not when will it be available?

**Comment by vesrah** [comment]
It looks like the API that exposes `EditorConfigProvider` that can be used to change Kendo settings is not yet available in the public version of Sitefinity, is there an ETA on this functionality being public?

**Comment by Gebov** [comment]
Hello @vesrah,

We are working on better categorization and documentation on which API's are available for reach Sitefinity Release. 

Regarding the EditorConfigProvider it will be available in the next Sitefinity Release, but I cannot say for sure when that would be.

Martin

**Comment by Gebov** [comment]
Hello, 

we added multiple tags on the repository that are synced with each Sitefinity release. Now you can browse the repository at the specific release and see which APIs are avaiable

Martin
